services:
  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    # mac_address: aa:59:de:11:2d:c0
    networks:
      iot:
        ipv4_address: 192.168.3.225
    ports:
      - "8091:8091" # http port
      - "3000:3000" # service port
    volumes:
      - /mnt/performance/docker/zwave-js-ui/usr/src/app/store:/usr/src/app/store
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_813026A9-if00-port0:/dev/zwave
    tty: true
    stop_signal: SIGINT
    restart: unless-stopped

networks:
  iot:
    external: true
