services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync-couchdb
    networks:
      external:
        ipv4_address: 192.168.5.230
    ports:
      - 5984:5984
    user: 950:544
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /mnt/performance/docker/obsidian-livesync/opt/couchdb/data:/opt/couchdb/data
      - /mnt/performance/docker/obsidian-livesync/opt/couchdb/etc/local.d:/opt/couchdb/etc/local.d
    restart: unless-stopped
networks:
  external:
    external: true