services:
  sshd:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: sshd
    mac_address: aa:bd:01:b0:b9:04
    networks:
      personal:
        ipv4_address: ${SSHD_IP}
    ports:
      - 2222:2222
    environment:
      - PUID=950
      - PGID=544
      - TZ=US/Eastern
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=false
      - USER_NAME=admin
      - LOG_STDOUT=true
      - DOCKER_MODS=linuxserver/mods:openssh-server-autossh|linuxserver/mods:openssh-server-git|linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=git-crypt|nix
    volumes:
      - ./config/.ssh/authorized_keys:/config/.ssh/authorized_keys
      - /mnt/performance/docker:/mnt/performance/docker
      - /mnt/performance/home/admin/Develop:/config/Develop
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
networks:
  personal:
    external: true
