services:
  podsync:
    image: mxpv/podsync:latest
    container_name: podsync
    user: "950:544"
    mac_address: aa:a6:01:99:c4:52
    networks:
      external:
        ipv4_address: 192.168.5.228
    ports:
      - "80:80"
    volumes:
      - /mnt/performance/docker/podsync/app/data:/app/data
      - /mnt/performance/docker/podsync/app/config.toml:/app/config.toml
    restart: unless-stopped

networks:
  external:
    external: true
