services:
  orb-docker:
    image: orbforge/orb:latest
    container_name: orb
    networks:
      iot:
        ipv4_address: 192.168.3.228
    volumes:
      - /mnt/performance/docker/orb/root/.config/orb:/root/.config/orb
    restart: always

networks:
  iot:
    external: true
