services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv
    container_name: isponsorblocktv
    networks:
      personal:
        ipv4_address: 192.168.6.235
    volumes:
      - /mnt/performance/docker/isponsorblocktv/app/data:/app/data
    restart: unless-stopped

networks:
  personal:
    external: true
